repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.1
    hooks:
      - id: prettier
        types_or:
          - typescript
          - javascript
          - json
          - markdown
          - yaml

  - repo: local
    hooks:
      - id: npm-lint
        name: npm lint
        entry: npm run lint --
        language: system
        types: [typescript, javascript]
        pass_filenames: true
